# Use the UBI 9 minimal image
FROM registry.access.redhat.com/ubi9/ubi-minimal

# Install Python 3, pip, and SQLite
RUN microdnf install -y python3 python3-pip sqlite && \
  microdnf clean all

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt and app code into the container
COPY . /app/

# Install Python dependencies using pip
RUN pip3 install --upgrade pip && \
  pip3 install --no-cache-dir -r /app/requirements.txt

# Expose the port your FastAPI app will run on
EXPOSE 8000

# Command to run the FastAPI application using Uvicorn
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
